---
# tasks file for ossec-agent

- name: Check if ossec-server is available
  command: 'ping -c 1 {{ ossec_server_name }}'
  ignore_errors: true
  changed_when: False
  register: ossec_server_ping
  check_mode: no

- name: Subscribe to required channels
  import_role:
    name: spacewalk-client
    tasks_from: channel.yml
  vars:
    channels: '{{ ossec_agent_rhn_channels }}'

- name: "Install {{ ossec_agent_package_name }}"
  package:
    name: "{{ ossec_agent_package_name }}"

- name: "Installing the ossec-agent.conf"
  template:
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: /var/ossec/etc/{{ ossec_agent_config_filename }}
    owner: root
    group: root
    mode: 0644
  notify: restart ossec-agent
  tags:
    - config

- name: Selinux file context on log file
  sefcontext:
    target: '/var/ossec/logs(/.*)?'
    setype: var_log_t
    state: present
  notify: restorecon ossec logs
  tags:
    - selinux

- name: "remove client.keys"
  file:
    path: /var/ossec/etc/client.keys
    state: absent
  when: ossec_agent_reconfigure
  tags:
    - config
  notify: restart ossec-agent

- name: "Check if client.keys exists"
  stat:
    path: /var/ossec/etc/client.keys
  register: check_keys
  tags:
    - config

- name: "Check if client.keys exists on ossec-server"
  stat:
    path: /var/ossec/etc/client.keys
  when: ossec_managed_server
  delegate_to: "{{ ossec_server_name }}"
  register: check_server_keys
  tags:
    - config

- name: "Starting auth daemon on server {{ ossec_server_name }}"
  service:
    name: ossec-authd
    state: started
  when:
    - ossec_managed_server and not check_keys.stat.exists and ossec_server_name|default("") != ""
    - ossec_server_ping.rc == 0
  delegate_to: "{{ ossec_server_name }}"
  #run_once: true
  tags:
    - config

- name: "Pausing"
  pause:
    minutes: 2
    prompt: 'Please execute the following command on your ossec-server: "service ossec-authd start"'
  check_mode: false
  when:
    - not ossec_managed_server and not check_keys.stat.exists or ossec_server_name|default("") == ""
    - ossec_server_ping.rc == 0

- name: "register client"
  shell: "/var/ossec/bin/agent-auth -m {{ ossec_server_ip|default(ossec_server_fqdn) }} -p 1515 -A '{{ ossec_agent_name|default(inventory_hostname) }}'"
  args:
    creates: /var/ossec/etc/client.keys
  when:
    - ossec_server_ping.rc == 0
  tags:
    - config

- name: "Check if client.keys exist now"
  stat:
    path: /var/ossec/etc/client.keys
  register: check_keys
  tags:
    - config

- name: Set permissions on client.keys file
  file:
    dest: /var/ossec/etc/client.keys
    mode: 0640
  check_mode: false
  when:
    - check_keys.stat.exists
    - ossec_server_ping.rc == 0

- name: "kill the auth-daemon on server {{ ossec_server_name }}"
  service:
    name: ossec-authd
    state: stopped
  delegate_to: "{{ ossec_server_name }}"
  when:
    - ossec_managed_server and not check_keys.stat.exists and ossec_server_name|default("") != ""
    - ossec_server_ping.rc == 0
  #run_once: true
  tags:
    - config

- name: "Pausing"
  pause:
    minutes: 2
    prompt: 'Please execute the following command on your ossec-server: "service ossec-authd stop"'
  when:
    - not ossec_managed_server and not check_keys.stat.exists and ossec_server_name|default("") == ""
    - ossec_server_ping.rc == 0

- name: "Restart ossec-remoted on server. If this is the first agent added it will not be running."
  shell: /var/ossec/bin/ossec-control restart
  delegate_to: "{{ ossec_server_name }}"
  when:
    - ossec_managed_server and not check_server_keys.stat.exists and ossec_server_name|default("") != ""
    - ossec_server_ping.rc == 0
  #run_once: true

- name: "Pausing"
  pause:
    minutes: 2
    prompt: 'Please execute the following command on your ossec-server: "/var/ossec/bin/ossec-control restart"'
  when:
    - not ossec_managed_server and not check_server_keys.stat.exists and ossec_server_name|default("") == ""
    - ossec_server_ping.rc == 0

- name: "Start ossec-agent if not already running"
  service:
    name: "{{ ossec_init_name }}"
    state: started
    enabled: yes
