---
# handlers file for ossec-agent

- name: restart ossec-agent
  service:
    name: "{{ ossec_init_name }}"
    state: restarted
    enabled: yes

- name: restorecon ossec logs
  command: /sbin/restorecon -R /var/ossec/logs
